Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316
      Tags:
        - Key: Name
          Value: A Simple Example